"""A new document from nothing, written the way Word writes a new blank document.

Every part is authored here, from the values in :mod:`.word_new` (generated by
``tools/e6_probe.py`` from a new blank document Word 16.106 for Mac made with ``make new
document`` and saved) and the tables below; nothing is copied from Word's template or the
user's ``Normal.dotm`` (ROADMAP.md, "Decisions", 4).  What Word writes, and so what is
written here:

* ``document.xml``: one empty paragraph and the section -- the page size, the margins,
  the header and footer distances, ``w:cols`` and ``w:docGrid w:linePitch="360"``;
* ``styles.xml``: the document defaults (the theme's minor font at 12 pt, kerning from
  1 pt, the language, contextual ligatures; 8 pt after, line spacing 278 auto), the 376
  latent styles, and the styles a new document has: Normal, headings 1-9 and their linked
  character styles, Default Paragraph Font, Normal Table, No List, Title, Subtitle, Quote,
  List Paragraph, Intense Emphasis, Intense Quote and Intense Reference -- with English
  Word's ids and names;
* ``settings.xml``: zoom, the default tab stop, the hyphenation zone, character spacing
  control, compatibility mode 15 with the five settings Word writes beside it, the math
  settings, the theme font language, the colour mapping, the decimal symbol and the list
  separator;
* ``webSettings.xml``, ``fontTable.xml`` (Aptos, Times New Roman, Aptos Display);
* the Office theme (Aptos Display / Aptos, the 2023 colours), written here from its values;
* ``docProps/core.xml`` and ``docProps/app.xml``.

**What depends on the locale.**  Word's new document follows its Normal template, which
follows the interface's locale: this Word (Dutch interface, metric) makes an A4 page with
2.5 cm margins (1417 twips), header and footer at 708, a default tab stop of 708 and a
hyphenation zone of 425, the decimal comma and the list separator ``;``.  :class:`Locale`
holds those values; :data:`METRIC` is the measured one and the default, :data:`US` is
English (United States) Word's (Letter, 1-inch margins, half-inch tabs and distances, no
hyphenation zone written, ``.`` and ``,``: Word's well-known defaults, not measured on this
machine).  The text language (``w:lang``, ``w:themeFontLang``) is a parameter of its own.

Left out on purpose: rsids (ROADMAP.md, "Decisions", 6) and ``w15:docId``, which Word adds
when it saves; ``w:view`` (Word writes the window's view, here Draft -- a file without one
opens in Print Layout); Word's localised names (the theme's "Kantoorthema", the linked
styles' "Kop 1 Char"), where English Word's are written.
"""

from __future__ import annotations

import io
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone

from . import word_new
from .ids import generate

# -- the locale --------------------------------------------------------------------------------


@dataclass(frozen=True)
class Locale:
    """What a new document takes from Word's locale (lengths in twips)."""

    margin: int = 1417
    header: int = 708
    footer: int = 708
    tab_stop: int = 708
    column_space: int = 708
    #: ``w:hyphenationZone``; ``None`` writes none (Word's default, 0.25 inch).
    hyphenation_zone: int | None = 425
    decimal_symbol: str = ","
    list_separator: str = ";"


#: Measured: Word 16.106 for Mac, Dutch interface, metric units.
METRIC = Locale()
#: English (United States) Word's defaults: Letter, 1 inch, half an inch.  Not measured here.
US = Locale(margin=1440, header=720, footer=720, tab_stop=720, column_space=720,
            hyphenation_zone=None, decimal_symbol=".", list_separator=",")

#: Named page sizes, twips (width, height), portrait.
PAGE_SIZES: dict[str, tuple[int, int]] = {
    "A4": (11906, 16838),
    "Letter": (12240, 15840),
    "Legal": (12240, 20160),
    "A5": (8391, 11906),
    "A3": (16838, 23811),
}

# -- namespaces --------------------------------------------------------------------------------

_W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
_NS = {
    "wpc": "http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas",
    "cx": "http://schemas.microsoft.com/office/drawing/2014/chartex",
    "cx1": "http://schemas.microsoft.com/office/drawing/2015/9/8/chartex",
    "cx2": "http://schemas.microsoft.com/office/drawing/2015/10/21/chartex",
    "cx3": "http://schemas.microsoft.com/office/drawing/2016/5/9/chartex",
    "cx4": "http://schemas.microsoft.com/office/drawing/2016/5/10/chartex",
    "cx5": "http://schemas.microsoft.com/office/drawing/2016/5/11/chartex",
    "cx6": "http://schemas.microsoft.com/office/drawing/2016/5/12/chartex",
    "cx7": "http://schemas.microsoft.com/office/drawing/2016/5/13/chartex",
    "cx8": "http://schemas.microsoft.com/office/drawing/2016/5/14/chartex",
    "mc": "http://schemas.openxmlformats.org/markup-compatibility/2006",
    "aink": "http://schemas.microsoft.com/office/drawing/2016/ink",
    "am3d": "http://schemas.microsoft.com/office/drawing/2017/model3d",
    "o": "urn:schemas-microsoft-com:office:office",
    "oel": "http://schemas.microsoft.com/office/2019/extlst",
    "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    "m": "http://schemas.openxmlformats.org/officeDocument/2006/math",
    "v": "urn:schemas-microsoft-com:vml",
    "wp14": "http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing",
    "wp": "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",
    "w10": "urn:schemas-microsoft-com:office:word",
    "w": _W,
    "w14": "http://schemas.microsoft.com/office/word/2010/wordml",
    "w15": "http://schemas.microsoft.com/office/word/2012/wordml",
    "w16cex": "http://schemas.microsoft.com/office/word/2018/wordml/cex",
    "w16cid": "http://schemas.microsoft.com/office/word/2016/wordml/cid",
    "w16": "http://schemas.microsoft.com/office/word/2018/wordml",
    "w16du": "http://schemas.microsoft.com/office/word/2023/wordml/word16du",
    "w16sdtdh": "http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash",
    "w16sdtfl": "http://schemas.microsoft.com/office/word/2024/wordml/sdtformatlock",
    "w16se": "http://schemas.microsoft.com/office/word/2015/wordml/symex",
    "wpg": "http://schemas.microsoft.com/office/word/2010/wordprocessingGroup",
    "wpi": "http://schemas.microsoft.com/office/word/2010/wordprocessingInk",
    "wne": "http://schemas.microsoft.com/office/word/2006/wordml",
    "wps": "http://schemas.microsoft.com/office/word/2010/wordprocessingShape",
    "sl": "http://schemas.openxmlformats.org/schemaLibrary/2006/main",
}
#: The extension namespaces every part Word writes declares, and lists as ignorable.
_EXTENSIONS = ("w14", "w15", "w16cex", "w16cid", "w16", "w16du", "w16sdtdh", "w16sdtfl", "w16se")
_IGNORABLE = "w14 w15 w16se w16cid w16 w16cex w16sdtdh w16sdtfl w16du"
_DOCUMENT_PREFIXES = ("wpc", "cx", "cx1", "cx2", "cx3", "cx4", "cx5", "cx6", "cx7", "cx8", "mc", "aink", "am3d",
                      "o", "oel", "r", "m", "v", "wp14", "wp", "w10", "w", "w14", "w15", "w16cex", "w16cid", "w16",
                      "w16du", "w16sdtdh", "w16sdtfl", "w16se", "wpg", "wpi", "wne", "wps")
_DECL = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'

CT = "application/vnd.openxmlformats-officedocument."
CT_DOCUMENT = CT + "wordprocessingml.document.main+xml"
CT_TEMPLATE = CT + "wordprocessingml.template.main+xml"
CT_STYLES = CT + "wordprocessingml.styles+xml"
CT_SETTINGS = CT + "wordprocessingml.settings+xml"
CT_WEB_SETTINGS = CT + "wordprocessingml.webSettings+xml"
CT_FONT_TABLE = CT + "wordprocessingml.fontTable+xml"
CT_THEME = CT + "theme+xml"
CT_CORE = "application/vnd.openxmlformats-package.core-properties+xml"
CT_APP = CT + "extended-properties+xml"
CT_RELS = "application/vnd.openxmlformats-package.relationships+xml"
_R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/"
REL_CORE = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"
REL_APP = _R + "extended-properties"


def _root(tag: str, prefixes: tuple[str, ...], ignorable: str | None = _IGNORABLE) -> str:
    declarations = " ".join(f'xmlns:{prefix}="{_NS[prefix]}"' for prefix in prefixes)
    return f"<{tag} {declarations}" + (f' mc:Ignorable="{ignorable}"' if ignorable else "") + ">"


def _escape(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def _xml(node: tuple) -> str:
    """An element from :mod:`.word_new`'s ``(tag, attributes, children)``."""
    tag, attributes, children = node
    attrs = "".join(f' {name}="{_escape(value)}"' for name, value in attributes)
    if not children:
        return f"<{tag}{attrs}/>"
    return f"<{tag}{attrs}>" + "".join(_xml(child) for child in children) + f"</{tag}>"


# -- styles ------------------------------------------------------------------------------------

#: English Word's ids where they are not the name's words run together.
_IDS = {"Normal Table": "TableNormal", "Default Paragraph Font": "DefaultParagraphFont", "No List": "NoList"}


def style_id(name: str) -> str:
    if name in _IDS:
        return _IDS[name]
    return "".join(word[:1].upper() + word[1:] for word in name.split())


def _with_language(node: tuple, language: str) -> tuple:
    tag, attributes, children = node
    if tag == "w:lang":
        attributes = tuple((k, language if k == "w:val" else v) for k, v in attributes)
    return (tag, attributes, tuple(_with_language(child, language) for child in children))


def _style_xml(entry: dict) -> str:
    flags = (' w:default="1"' if entry.get("default") else "") + (' w:customStyle="1"' if entry.get("custom") else "")
    out = [f'<w:style w:type="{entry["type"]}"{flags} w:styleId="{style_id(entry["name"])}">'
           f'<w:name w:val="{_escape(entry["name"])}"/>']
    for child in entry["children"]:
        if len(child) == 1:
            out.append(f"<{child[0]}/>")
        elif len(child) == 2:
            tag, value = child
            out.append(f'<{tag} w:val="{style_id(value) if isinstance(value, str) else value}"/>')
        else:
            out.append(_xml(child))
    out.append("</w:style>")
    return "".join(out)


def _latent_xml() -> str:
    attributes = "".join(f' {name}="{value}"' for name, value in word_new.LATENT_DEFAULTS)
    rows = []
    for name, priority, flags in word_new.LATENT:
        # Word's attribute order: name, locked, semiHidden, uiPriority, unhideWhenUsed, qFormat.
        attrs = f' w:name="{_escape(name)}"'
        attrs += ' w:locked="1"' if "l" in flags else ""
        attrs += ' w:semiHidden="1"' if "s" in flags else ""
        attrs += f' w:uiPriority="{priority}"' if priority is not None else ""
        attrs += ' w:unhideWhenUsed="1"' if "u" in flags else ""
        attrs += ' w:qFormat="1"' if "q" in flags else ""
        rows.append(f"<w:lsdException{attrs}/>")
    return f"<w:latentStyles{attributes}>" + "".join(rows) + "</w:latentStyles>"


def styles_xml(language: str) -> str:
    return (_DECL + _root("w:styles", ("mc", "r", "w") + _EXTENSIONS)
            + _xml(_with_language(word_new.DOC_DEFAULTS, language)) + _latent_xml()
            + "".join(_style_xml(entry) for entry in word_new.STYLES) + "</w:styles>")


# -- settings, web settings, fonts ---------------------------------------------------------------

_COMPAT_URI = "http://schemas.microsoft.com/office/word"


def settings_xml(language: str, locale: Locale) -> str:
    compat = "".join(f'<w:compatSetting w:name="{name}" w:uri="{_COMPAT_URI}" w:val="{value}"/>'
                     for name, value in word_new.COMPAT)
    mapping = "".join(f' {name}="{value}"' for name, value in word_new.COLOR_MAPPING)
    zone = f'<w:hyphenationZone w:val="{locale.hyphenation_zone}"/>' if locale.hyphenation_zone is not None else ""
    return (_DECL + _root("w:settings", ("mc", "o", "r", "m", "v", "w10", "w") + _EXTENSIONS + ("sl",))
            + '<w:zoom w:percent="100"/>'
            + f'<w:defaultTabStop w:val="{locale.tab_stop}"/>{zone}'
            + '<w:characterSpacingControl w:val="doNotCompress"/>'
            + f"<w:compat>{compat}</w:compat>" + _xml(word_new.MATH)
            + f'<w:themeFontLang w:val="{_escape(language)}"/><w:clrSchemeMapping{mapping}/>'
            + f'<w:decimalSymbol w:val="{_escape(locale.decimal_symbol)}"/>'
            + f'<w:listSeparator w:val="{_escape(locale.list_separator)}"/>'
            + "<w15:chartTrackingRefBased/></w:settings>")


def web_settings_xml() -> str:
    return (_DECL + _root("w:webSettings", ("mc", "r", "w") + _EXTENSIONS)
            + "".join(f"<{tag}/>" for tag in word_new.WEB_SETTINGS) + "</w:webSettings>")


def font_table_xml() -> str:
    return (_DECL + _root("w:fonts", ("mc", "r", "w") + _EXTENSIONS)
            + "".join(_xml(font) for font in word_new.FONTS) + "</w:fonts>")


# -- the theme ---------------------------------------------------------------------------------

THEME_NAME = "Office Theme"
#: The Office theme's colours (Office 2023 onwards): name -> sRGB, or a system colour.
THEME_COLORS: tuple[tuple[str, str], ...] = (
    ("dk1", "sys:windowText:000000"), ("lt1", "sys:window:FFFFFF"),
    ("dk2", "0E2841"), ("lt2", "E8E8E8"),
    ("accent1", "156082"), ("accent2", "E97132"), ("accent3", "196B24"),
    ("accent4", "0F9ED5"), ("accent5", "A02B93"), ("accent6", "4EA72E"),
    ("hlink", "467886"), ("folHlink", "96607D"),
)
MAJOR_FONT, MINOR_FONT = "Aptos Display", "Aptos"
_APTOS_PANOSE = "02110004020202020204"
#: Per-script fallback faces of the Office font scheme: script -> (major, minor).
SCRIPT_FONTS: tuple[tuple[str, str, str], ...] = (
    ("Jpan", "游ゴシック Light", "游明朝"), ("Hang", "맑은 고딕", "맑은 고딕"),
    ("Hans", "等线 Light", "等线"), ("Hant", "新細明體", "新細明體"),
    ("Arab", "Times New Roman", "Arial"), ("Hebr", "Times New Roman", "Arial"),
    ("Thai", "Angsana New", "Cordia New"), ("Ethi", "Nyala", "Nyala"),
    ("Beng", "Vrinda", "Vrinda"), ("Gujr", "Shruti", "Shruti"),
    ("Khmr", "MoolBoran", "DaunPenh"), ("Knda", "Tunga", "Tunga"),
    ("Guru", "Raavi", "Raavi"), ("Cans", "Euphemia", "Euphemia"),
    ("Cher", "Plantagenet Cherokee", "Plantagenet Cherokee"),
    ("Yiii", "Microsoft Yi Baiti", "Microsoft Yi Baiti"),
    ("Tibt", "Microsoft Himalaya", "Microsoft Himalaya"), ("Thaa", "MV Boli", "MV Boli"),
    ("Deva", "Mangal", "Mangal"), ("Telu", "Gautami", "Gautami"), ("Taml", "Latha", "Latha"),
    ("Syrc", "Estrangelo Edessa", "Estrangelo Edessa"), ("Orya", "Kalinga", "Kalinga"),
    ("Mlym", "Kartika", "Kartika"), ("Laoo", "DokChampa", "DokChampa"),
    ("Sinh", "Iskoola Pota", "Iskoola Pota"), ("Mong", "Mongolian Baiti", "Mongolian Baiti"),
    ("Viet", "Times New Roman", "Arial"), ("Uigh", "Microsoft Uighur", "Microsoft Uighur"),
    ("Geor", "Sylfaen", "Sylfaen"), ("Armn", "Arial", "Arial"),
    ("Bugi", "Leelawadee UI", "Leelawadee UI"),
    ("Bopo", "Microsoft JhengHei", "Microsoft JhengHei"),
    ("Java", "Javanese Text", "Javanese Text"), ("Lisu", "Segoe UI", "Segoe UI"),
    ("Mymr", "Myanmar Text", "Myanmar Text"), ("Nkoo", "Ebrima", "Ebrima"),
    ("Olck", "Nirmala UI", "Nirmala UI"), ("Osma", "Ebrima", "Ebrima"),
    ("Phag", "Phagspa", "Phagspa"), ("Syrn", "Estrangelo Edessa", "Estrangelo Edessa"),
    ("Syrj", "Estrangelo Edessa", "Estrangelo Edessa"),
    ("Syre", "Estrangelo Edessa", "Estrangelo Edessa"), ("Sora", "Nirmala UI", "Nirmala UI"),
    ("Tale", "Microsoft Tai Le", "Microsoft Tai Le"),
    ("Talu", "Microsoft New Tai Lue", "Microsoft New Tai Lue"), ("Tfng", "Ebrima", "Ebrima"),
)
#: The fill style list's two gradients and the background list's one: (position, modifiers).
_FILL_GRADIENTS = (
    ((0, (("lumMod", 110000), ("satMod", 105000), ("tint", 67000))),
     (50000, (("lumMod", 105000), ("satMod", 103000), ("tint", 73000))),
     (100000, (("lumMod", 105000), ("satMod", 109000), ("tint", 81000)))),
    ((0, (("satMod", 103000), ("lumMod", 102000), ("tint", 94000))),
     (50000, (("satMod", 110000), ("lumMod", 100000), ("shade", 100000))),
     (100000, (("lumMod", 99000), ("satMod", 120000), ("shade", 78000)))),
)
_BACKGROUND_GRADIENT = (
    (0, (("tint", 93000), ("satMod", 150000), ("shade", 98000), ("lumMod", 102000))),
    (50000, (("tint", 98000), ("satMod", 130000), ("shade", 90000), ("lumMod", 103000))),
    (100000, (("shade", 63000), ("satMod", 120000))),
)
#: Line widths of the three line styles, EMU: Word's (PowerPoint's are wider).
LINE_WIDTHS = (6350, 12700, 19050)
#: The theme family Word names its Office theme by.
THEME_FAMILY = ("Office Theme", "{2E142A2C-CD16-42D6-873A-C26D2A0506FA}", "{1BDDFF52-6CD6-40A5-AB3C-68EB2F1E4D0A}")


def _gradient(stops) -> str:
    out = ['<a:gradFill rotWithShape="1"><a:gsLst>']
    for position, modifiers in stops:
        mods = "".join(f'<a:{name} val="{value}"/>' for name, value in modifiers)
        out.append(f'<a:gs pos="{position}"><a:schemeClr val="phClr">{mods}</a:schemeClr></a:gs>')
    out.append('</a:gsLst><a:lin ang="5400000" scaled="0"/></a:gradFill>')
    return "".join(out)


def theme_xml() -> str:
    a = "http://schemas.openxmlformats.org/drawingml/2006/main"
    out = [_DECL, f'<a:theme xmlns:a="{a}" name="{THEME_NAME}"><a:themeElements><a:clrScheme name="Office">']
    for name, value in THEME_COLORS:
        if value.startswith("sys:"):
            _, system, last = value.split(":")
            out.append(f'<a:{name}><a:sysClr val="{system}" lastClr="{last}"/></a:{name}>')
        else:
            out.append(f'<a:{name}><a:srgbClr val="{value}"/></a:{name}>')
    out.append('</a:clrScheme><a:fontScheme name="Office">')
    for tag, face, column in (("majorFont", MAJOR_FONT, 1), ("minorFont", MINOR_FONT, 2)):
        out.append(f'<a:{tag}><a:latin typeface="{face}" panose="{_APTOS_PANOSE}"/><a:ea typeface=""/>'
                   '<a:cs typeface=""/>')
        out += [f'<a:font script="{entry[0]}" typeface="{entry[column]}"/>' for entry in SCRIPT_FONTS]
        out.append(f"</a:{tag}>")
    out.append('</a:fontScheme><a:fmtScheme name="Office"><a:fillStyleLst>'
               '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>')
    out += [_gradient(stops) for stops in _FILL_GRADIENTS]
    out.append("</a:fillStyleLst><a:lnStyleLst>")
    for width in LINE_WIDTHS:
        out.append(f'<a:ln w="{width}" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/>'
                   '</a:solidFill><a:prstDash val="solid"/><a:miter lim="800000"/></a:ln>')
    out.append('</a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle>'
               '<a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst>'
               '<a:outerShdw blurRad="57150" dist="19050" dir="5400000" algn="ctr" rotWithShape="0">'
               '<a:srgbClr val="000000"><a:alpha val="63000"/></a:srgbClr></a:outerShdw></a:effectLst>'
               "</a:effectStyle></a:effectStyleLst><a:bgFillStyleLst>"
               '<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>'
               '<a:solidFill><a:schemeClr val="phClr"><a:tint val="95000"/><a:satMod val="170000"/>'
               "</a:schemeClr></a:solidFill>")
    out.append(_gradient(_BACKGROUND_GRADIENT))
    family, family_id, vid = THEME_FAMILY
    out.append("</a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/>"
               '<a:extLst><a:ext uri="{05A4C25C-085E-4340-85A3-A5531E510DB2}">'
               '<thm15:themeFamily xmlns:thm15="http://schemas.microsoft.com/office/thememl/2012/main" '
               f'name="{family}" id="{family_id}" vid="{vid}"/></a:ext></a:extLst></a:theme>')
    return "".join(out)


# -- the document --------------------------------------------------------------------------------


def page_size(page, orientation: str = "portrait") -> tuple[int, int]:
    """``(width, height)`` in twips: a name of :data:`PAGE_SIZES`, or ``(width, height)`` in
    points; landscape puts the longer side across."""
    if isinstance(page, str):
        if page not in PAGE_SIZES:
            raise ValueError(f"unknown page size {page!r}: one of {', '.join(PAGE_SIZES)}, or (width, height)")
        width, height = PAGE_SIZES[page]
    else:
        try:
            width, height = (round(float(side) * 20) for side in page)
        except (TypeError, ValueError):
            raise ValueError("a page size is a name or (width, height) in points") from None
        if not (1440 <= width <= 31680 and 1440 <= height <= 31680):
            raise ValueError("a page side is between 72 and 1584 points (Word's 1 to 22 inches)")
    if orientation not in ("portrait", "landscape"):
        raise ValueError("orientation is 'portrait' or 'landscape'")
    if orientation == "landscape":
        width, height = max(width, height), min(width, height)
    return width, height


def document_xml(width: int, height: int, orientation: str, locale: Locale) -> str:
    para_id, text_id = generate("word/document.xml", set(), 2)
    orient = ' w:orient="landscape"' if orientation == "landscape" else ""
    m = locale.margin
    return (_DECL + _root("w:document", _DOCUMENT_PREFIXES, _IGNORABLE + " wp14")
            + f'<w:body><w:p w14:paraId="{para_id}" w14:textId="{text_id}"/>'
            + f'<w:sectPr><w:pgSz w:w="{width}" w:h="{height}"{orient}/>'
            + f'<w:pgMar w:top="{m}" w:right="{m}" w:bottom="{m}" w:left="{m}" w:header="{locale.header}" '
            + f'w:footer="{locale.footer}" w:gutter="0"/><w:cols w:space="{locale.column_space}"/>'
            + '<w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>')


def _rels(relationships: list[tuple[str, str, str]]) -> str:
    items = "".join(f'<Relationship Id="{rid}" Type="{kind}" Target="{target}"/>'
                    for rid, kind, target in relationships)
    return (_DECL + '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            + items + "</Relationships>")


def _content_types(overrides: list[tuple[str, str]]) -> str:
    return (_DECL + '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
            f'<Default Extension="rels" ContentType="{CT_RELS}"/><Default Extension="xml" ContentType="application/xml"/>'
            + "".join(f'<Override PartName="/{part}" ContentType="{kind}"/>' for part, kind in overrides)
            + "</Types>")


def build(*, page="A4", orientation: str = "portrait", language: str = "en-US", locale: Locale | None = None,
          title: str | None = None, author: str | None = None, created: datetime | None = None) -> bytes:
    """The whole package of a new blank document, as bytes."""
    from .properties import app_xml, core_xml

    if locale is None:
        locale = US if page == "Letter" else METRIC
    width, height = page_size(page, orientation)
    created = (created or datetime.now(timezone.utc)).replace(microsecond=0)
    parts = [
        ("_rels/.rels", _rels([("rId3", REL_APP, "docProps/app.xml"), ("rId2", REL_CORE, "docProps/core.xml"),
                               ("rId1", _R + "officeDocument", "word/document.xml")])),
        ("word/document.xml", document_xml(width, height, orientation, locale)),
        ("word/_rels/document.xml.rels", _rels([("rId3", _R + "webSettings", "webSettings.xml"),
                                                ("rId2", _R + "settings", "settings.xml"),
                                                ("rId1", _R + "styles", "styles.xml"),
                                                ("rId5", _R + "theme", "theme/theme1.xml"),
                                                ("rId4", _R + "fontTable", "fontTable.xml")])),
        ("word/theme/theme1.xml", theme_xml()),
        ("word/settings.xml", settings_xml(language, locale)),
        ("word/styles.xml", styles_xml(language)),
        ("word/webSettings.xml", web_settings_xml()),
        ("word/fontTable.xml", font_table_xml()),
        ("docProps/core.xml", core_xml(title=title, author=author, created=created)),
        ("docProps/app.xml", app_xml()),
    ]
    overrides = [("word/document.xml", CT_DOCUMENT), ("word/styles.xml", CT_STYLES),
                 ("word/settings.xml", CT_SETTINGS), ("word/webSettings.xml", CT_WEB_SETTINGS),
                 ("word/fontTable.xml", CT_FONT_TABLE), ("word/theme/theme1.xml", CT_THEME),
                 ("docProps/core.xml", CT_CORE), ("docProps/app.xml", CT_APP)]
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, data in [("[Content_Types].xml", _content_types(overrides))] + parts:
            entry = zipfile.ZipInfo(path, date_time=(1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.create_system = 3  # ZipInfo stamps the platform; the same bytes everywhere
            archive.writestr(entry, data.encode("utf-8") if isinstance(data, str) else data)
    return buffer.getvalue()


__all__ = ["Locale", "METRIC", "PAGE_SIZES", "US", "build", "page_size", "style_id"]
