"""Writing a built-in style the document does not define, as Word writes it on first use.

The definitions are measured (:mod:`docx_agent.edit.word_styles`, generated by
``tools/e1_probe.py``: Word 16.106 applied each built-in style to a probe document and its
definitions were read back).  They point at other styles by *name* -- ``w:basedOn`` Normal,
``w:next`` Normal, ``w:link`` "Heading 2 Char" -- and are written with the ids the target
document gives those names, so a Dutch template's ``Standaard`` is what a new Heading 2 is
based on.  What a definition points at and the document lacks is written too (a heading's
linked character style); a list style (List Bullet, List Number...) gets the list Word
gives it, a single-level definition whose level names the style.

A new style's id is English Word's (``Heading2``, ``Heading2Char``, ``ListBullet``), numbered
if the document already uses it for another style.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from lxml import etree

from .word_comment_styles import STYLES as _COMMENT_STYLES
from .word_styles import STYLES as _STYLES
from .word_table_styles import STYLES as _TABLE_STYLES
from .word_toc_styles import STYLES as _TOC_STYLES

#: Every measured definition: E1's (``e1_probe.py``), the comment styles (``e3_probe.py``),
#: Table Grid (``e2_probe.py``) and TOC 1-9 (``e4_probe.py``).
STYLES = {**_STYLES, **_COMMENT_STYLES, **_TABLE_STYLES, **_TOC_STYLES}
#: English Word's ids where they are not the name's words run together.
_ENGLISH_IDS = {
    "annotation text": "CommentText", "Annotation Text Char": "CommentTextChar",
    "annotation reference": "CommentReference", "annotation subject": "CommentSubject",
    "Annotation Subject Char": "CommentSubjectChar",
    **{f"toc {n}": f"TOC{n}" for n in range(1, 10)},
}

if TYPE_CHECKING:  # pragma: no cover
    from .styles import Styles

_W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


def lookup(name: str) -> tuple[str, dict] | None:
    """The measured definition ``name`` names (any case), with its canonical name."""
    if name in STYLES:
        return name, STYLES[name]
    wanted = name.casefold()
    for key, value in STYLES.items():
        if key.casefold() == wanted:
            return key, value
    return None


def english_id(name: str) -> str:
    if name in _ENGLISH_IDS:
        return _ENGLISH_IDS[name]
    return "".join(word[:1].upper() + word[1:] for word in name.split())


def plan(name: str, kind: str, styles: "Styles") -> list[tuple[str, str, dict]] | None:
    """What adding the built-in style ``name`` writes: ``(canonical name, new id,
    definition)`` for it and every style it points at that the document lacks, or ``None``
    if Word has no built-in ``kind`` style by that name."""
    found = lookup(name)
    if found is None or found[1]["type"] != kind:
        return None
    taken = {style.id.casefold() for style in styles}
    out: list[tuple[str, str, dict]] = []
    pending = [found[0]]
    while pending:
        current = pending.pop(0)
        if any(current == planned for planned, _, _ in out) or styles.find(current) is not None:
            continue
        entry = lookup(current)
        if entry is None:
            continue
        canonical, definition = entry
        style_id = english_id(canonical)
        number = 1
        while style_id.casefold() in taken:
            number += 1
            style_id = f"{english_id(canonical)}{number}"
        taken.add(style_id.casefold())
        out.append((canonical, style_id, definition))
        pending += list(definition["refs"].values())
    return out


def definition_chain(name: str, kind: str, styles: "Styles") -> list[tuple[str, str]] | None:
    """``(id, name)`` of what :func:`write` would add, the asked-for style first; ``None``
    if Word has no built-in ``kind`` style ``name``."""
    planned = plan(name, kind, styles)
    if planned is None:
        return None
    return [(style_id, canonical) for canonical, style_id, _ in planned]


def write(name: str, kind: str, styles: "Styles") -> str:
    """Add the built-in style ``name`` (and what it needs); returns its id."""
    from . import numbering as _numbering

    planned = plan(name, kind, styles)
    if not planned:
        found = styles.find(name, kind)
        if found is None:
            raise KeyError(name)
        return found.id
    ids = {canonical.casefold(): style_id for canonical, style_id, _ in planned}

    def resolve(target: str) -> str | None:
        if target.casefold() in ids:
            return ids[target.casefold()]
        existing = styles.find(target)
        return existing.id if existing is not None else None

    document = styles._document
    for canonical, style_id, definition in planned:
        xml = definition["xml"].replace("{id}", style_id)
        node = etree.fromstring(xml)
        for tag in ("basedOn", "next", "link"):
            child = node.find(_W + tag)
            if child is None:
                continue
            target = resolve(definition["refs"].get(tag, ""))
            if target is None:
                node.remove(child)
            else:
                child.set(_W + "val", target)
        if "numbering" in definition:
            numbering = _numbering.Numbering(document)
            abstract_id = max(numbering.abstracts(), default=-1) + 1
            seed = f"style\0{style_id}\0{abstract_id}"
            abstract = definition["numbering"]
            for placeholder, value in (("{abstract}", str(abstract_id)), ("{id}", style_id),
                                       ("{nsid}", _numbering._nsid(document, seed + "nsid")),
                                       ("{tmpl}", _numbering._nsid(document, seed + "tmpl"))):
                abstract = abstract.replace(placeholder, value)
            _numbering.add_abstract(document, etree.fromstring(abstract))
            num_id = _numbering.add_num(document, abstract_id)
            document.package.mark_dirty(_numbering.Numbering(document).part)
            for num in node.iter(_W + "numId"):
                if num.get(_W + "val") == "{num}":
                    num.set(_W + "val", str(num_id))
        styles._append(node)
    return planned[0][1]
