"""Word's Table Grid style, as Word 16.106 writes it on first use.

Generated by ``tools/e2_probe.py`` from the probe Word saved (the observations are in
``tests/observations/e2-word.json``); do not edit by hand.  The same form as
``word_styles.py``: keyed by ``w:name``, ``{id}`` and the references filled in when written.
"""

STYLES: dict[str, dict] = {'Table Grid': {'refs': {'basedOn': 'Normal Table'},
                'type': 'table',
                'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                       'w:type="table" w:styleId="{id}"><w:name w:val="Table Grid"/><w:basedOn '
                       'w:val="{basedOn}"/><w:uiPriority w:val="39"/><w:pPr><w:spacing w:after="0" '
                       'w:line="240" w:lineRule="auto"/></w:pPr><w:tblPr><w:tblBorders><w:top w:val="single" '
                       'w:sz="4" w:space="0" w:color="auto"/><w:left w:val="single" w:sz="4" w:space="0" '
                       'w:color="auto"/><w:bottom w:val="single" w:sz="4" w:space="0" '
                       'w:color="auto"/><w:right w:val="single" w:sz="4" w:space="0" '
                       'w:color="auto"/><w:insideH w:val="single" w:sz="4" w:space="0" '
                       'w:color="auto"/><w:insideV w:val="single" w:sz="4" w:space="0" '
                       'w:color="auto"/></w:tblBorders></w:tblPr></w:style>'}}
