"""Word's built-in style definitions, as Word 16.106 writes them on a style's first use.

Generated by ``tools/e1_probe.py`` from what Word wrote into a probe document (the
observations are in ``tests/observations/e1-word.json``); do not edit by hand.  Keyed by
``w:name``; each entry's ``xml`` has ``{id}``, ``{basedOn}``, ``{next}`` and ``{link}`` where
the document's own ids go, and ``refs`` names the styles those point at.
"""

STYLES: dict[str, dict] = {'Bibliography': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
                  'type': 'paragraph',
                  'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                         'w:type="paragraph" w:styleId="{id}"><w:name w:val="Bibliography"/><w:basedOn '
                         'w:val="{basedOn}"/><w:next w:val="{next}"/><w:uiPriority '
                         'w:val="37"/><w:unhideWhenUsed/></w:style>'},
 'Block Text': {'refs': {'basedOn': 'Normal'},
                'type': 'paragraph',
                'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                       'w:type="paragraph" w:styleId="{id}"><w:name w:val="Block Text"/><w:basedOn '
                       'w:val="{basedOn}"/><w:uiPriority '
                       'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:pBdr><w:top w:val="single" w:sz="2" '
                       'w:space="10" w:color="4472C4" w:themeColor="accent1"/><w:left w:val="single" '
                       'w:sz="2" w:space="10" w:color="4472C4" w:themeColor="accent1"/><w:bottom '
                       'w:val="single" w:sz="2" w:space="10" w:color="4472C4" '
                       'w:themeColor="accent1"/><w:right w:val="single" w:sz="2" w:space="10" '
                       'w:color="4472C4" w:themeColor="accent1"/></w:pBdr><w:ind w:left="1152" '
                       'w:right="1152"/></w:pPr><w:rPr><w:rFonts w:asciiTheme="minorHAnsi" '
                       'w:eastAsiaTheme="minorEastAsia" w:hAnsiTheme="minorHAnsi" '
                       'w:cstheme="minorBidi"/><w:i/><w:iCs/><w:color w:val="4472C4" '
                       'w:themeColor="accent1"/></w:rPr></w:style>'},
 'Body Text': {'refs': {'basedOn': 'Normal', 'link': 'Body Text Char'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="Body Text"/><w:basedOn '
                      'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="120"/></w:pPr></w:style>'},
 'Body Text Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'Body Text'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Body Text '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="99"/></w:style>'},
 'Book Title': {'refs': {'basedOn': 'Default Paragraph Font'},
                'type': 'character',
                'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                       'w:type="character" w:styleId="{id}"><w:name w:val="Book Title"/><w:basedOn '
                       'w:val="{basedOn}"/><w:uiPriority '
                       'w:val="33"/><w:qFormat/><w:rPr><w:b/><w:bCs/><w:i/><w:iCs/><w:spacing '
                       'w:val="5"/></w:rPr></w:style>'},
 'Emphasis': {'refs': {'basedOn': 'Default Paragraph Font'},
              'type': 'character',
              'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                     'w:type="character" w:styleId="{id}"><w:name w:val="Emphasis"/><w:basedOn '
                     'w:val="{basedOn}"/><w:uiPriority '
                     'w:val="20"/><w:qFormat/><w:rPr><w:i/><w:iCs/></w:rPr></w:style>'},
 'Endnote Text Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'endnote text'},
                       'type': 'character',
                       'xml': '<w:style '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Endnote '
                              'Text Char"/><w:basedOn w:val="{basedOn}"/><w:link '
                              'w:val="{link}"/><w:uiPriority w:val="99"/><w:rPr><w:sz w:val="20"/><w:szCs '
                              'w:val="20"/></w:rPr></w:style>'},
 'FollowedHyperlink': {'refs': {'basedOn': 'Default Paragraph Font'},
                       'type': 'character',
                       'xml': '<w:style '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:type="character" w:styleId="{id}"><w:name '
                              'w:val="FollowedHyperlink"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                              'w:val="99"/><w:unhideWhenUsed/><w:rPr><w:color w:val="954F72" '
                              'w:themeColor="followedHyperlink"/><w:u w:val="single"/></w:rPr></w:style>'},
 'Footer Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'footer'},
                 'type': 'character',
                 'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                        'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Footer '
                        'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                        'w:val="99"/></w:style>'},
 'Footnote Text Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'footnote text'},
                        'type': 'character',
                        'xml': '<w:style '
                               'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                               'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name '
                               'w:val="Footnote Text Char"/><w:basedOn w:val="{basedOn}"/><w:link '
                               'w:val="{link}"/><w:uiPriority w:val="99"/><w:rPr><w:sz w:val="20"/><w:szCs '
                               'w:val="20"/></w:rPr></w:style>'},
 'HTML Code': {'refs': {'basedOn': 'Default Paragraph Font'},
               'type': 'character',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="character" w:styleId="{id}"><w:name w:val="HTML Code"/><w:basedOn '
                      'w:val="{basedOn}"/><w:uiPriority w:val="99"/><w:unhideWhenUsed/><w:rPr><w:rFonts '
                      'w:ascii="Consolas" w:hAnsi="Consolas" w:cs="Consolas"/><w:sz w:val="20"/><w:szCs '
                      'w:val="20"/></w:rPr></w:style>'},
 'HTML Preformatted': {'refs': {'basedOn': 'Normal', 'link': 'HTML Preformatted Char'},
                       'type': 'paragraph',
                       'xml': '<w:style '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:type="paragraph" w:styleId="{id}"><w:name w:val="HTML '
                              'Preformatted"/><w:basedOn w:val="{basedOn}"/><w:link '
                              'w:val="{link}"/><w:uiPriority '
                              'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="0" w:line="240" '
                              'w:lineRule="auto"/></w:pPr><w:rPr><w:rFonts w:ascii="Consolas" '
                              'w:hAnsi="Consolas"/><w:sz w:val="20"/><w:szCs w:val="20"/></w:rPr></w:style>'},
 'HTML Preformatted Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'HTML Preformatted'},
                            'type': 'character',
                            'xml': '<w:style '
                                   'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                   'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name '
                                   'w:val="HTML Preformatted Char"/><w:basedOn w:val="{basedOn}"/><w:link '
                                   'w:val="{link}"/><w:uiPriority w:val="99"/><w:rPr><w:rFonts '
                                   'w:ascii="Consolas" w:hAnsi="Consolas"/><w:sz w:val="20"/><w:szCs '
                                   'w:val="20"/></w:rPr></w:style>'},
 'Header Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'header'},
                 'type': 'character',
                 'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                        'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Header '
                        'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                        'w:val="99"/></w:style>'},
 'Heading 1 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 1'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 1 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:color w:val="2F5496" w:themeColor="accent1" '
                           'w:themeShade="BF"/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr></w:style>'},
 'Heading 2 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 2'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 2 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:color w:val="2F5496" w:themeColor="accent1" '
                           'w:themeShade="BF"/><w:sz w:val="26"/><w:szCs w:val="26"/></w:rPr></w:style>'},
 'Heading 3 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 3'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 3 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:color w:val="1F3763" w:themeColor="accent1" '
                           'w:themeShade="7F"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:style>'},
 'Heading 4 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 4'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 4 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:i/><w:iCs/><w:color w:val="2F5496" '
                           'w:themeColor="accent1" w:themeShade="BF"/></w:rPr></w:style>'},
 'Heading 5 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 5'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 5 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:color w:val="2F5496" w:themeColor="accent1" '
                           'w:themeShade="BF"/></w:rPr></w:style>'},
 'Heading 6 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 6'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 6 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:color w:val="1F3763" w:themeColor="accent1" '
                           'w:themeShade="7F"/></w:rPr></w:style>'},
 'Heading 7 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 7'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 7 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:i/><w:iCs/><w:color w:val="1F3763" '
                           'w:themeColor="accent1" w:themeShade="7F"/></w:rPr></w:style>'},
 'Heading 8 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 8'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 8 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:color w:val="272727" w:themeColor="text1" '
                           'w:themeTint="D8"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:style>'},
 'Heading 9 Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'heading 9'},
                    'type': 'character',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Heading 9 '
                           'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                           'w:val="9"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                           'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                           'w:cstheme="majorBidi"/><w:i/><w:iCs/><w:color w:val="272727" '
                           'w:themeColor="text1" w:themeTint="D8"/><w:sz w:val="21"/><w:szCs '
                           'w:val="21"/></w:rPr></w:style>'},
 'Hyperlink': {'refs': {'basedOn': 'Default Paragraph Font'},
               'type': 'character',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="character" w:styleId="{id}"><w:name w:val="Hyperlink"/><w:basedOn '
                      'w:val="{basedOn}"/><w:uiPriority w:val="99"/><w:unhideWhenUsed/><w:rPr><w:color '
                      'w:val="0563C1" w:themeColor="hyperlink"/><w:u w:val="single"/></w:rPr></w:style>'},
 'Intense Emphasis': {'refs': {'basedOn': 'Default Paragraph Font'},
                      'type': 'character',
                      'xml': '<w:style '
                             'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                             'w:type="character" w:styleId="{id}"><w:name w:val="Intense '
                             'Emphasis"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                             'w:val="21"/><w:qFormat/><w:rPr><w:i/><w:iCs/><w:color w:val="4472C4" '
                             'w:themeColor="accent1"/></w:rPr></w:style>'},
 'Intense Quote': {'refs': {'basedOn': 'Normal', 'link': 'Intense Quote Char', 'next': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="Intense Quote"/><w:basedOn '
                          'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                          'w:val="30"/><w:qFormat/><w:pPr><w:pBdr><w:top w:val="single" w:sz="4" '
                          'w:space="10" w:color="4472C4" w:themeColor="accent1"/><w:bottom w:val="single" '
                          'w:sz="4" w:space="10" w:color="4472C4" '
                          'w:themeColor="accent1"/></w:pBdr><w:spacing w:before="360" w:after="360"/><w:ind '
                          'w:left="864" w:right="864"/><w:jc '
                          'w:val="center"/></w:pPr><w:rPr><w:i/><w:iCs/><w:color w:val="4472C4" '
                          'w:themeColor="accent1"/></w:rPr></w:style>'},
 'Intense Quote Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'Intense Quote'},
                        'type': 'character',
                        'xml': '<w:style '
                               'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                               'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Intense '
                               'Quote Char"/><w:basedOn w:val="{basedOn}"/><w:link '
                               'w:val="{link}"/><w:uiPriority w:val="30"/><w:rPr><w:i/><w:iCs/><w:color '
                               'w:val="4472C4" w:themeColor="accent1"/></w:rPr></w:style>'},
 'Intense Reference': {'refs': {'basedOn': 'Default Paragraph Font'},
                       'type': 'character',
                       'xml': '<w:style '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:type="character" w:styleId="{id}"><w:name w:val="Intense '
                              'Reference"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                              'w:val="32"/><w:qFormat/><w:rPr><w:b/><w:bCs/><w:smallCaps/><w:color '
                              'w:val="4472C4" w:themeColor="accent1"/><w:spacing '
                              'w:val="5"/></w:rPr></w:style>'},
 'List Bullet': {'numbering': '<w:abstractNum '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                              'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                              'w:val="1"/><w:numFmt w:val="bullet"/><w:pStyle w:val="{id}"/><w:lvlText '
                              'w:val="\uf0b7"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                              'w:pos="360"/></w:tabs><w:ind w:left="360" '
                              'w:hanging="360"/></w:pPr><w:rPr><w:rFonts w:ascii="Symbol" w:hAnsi="Symbol" '
                              'w:hint="default"/></w:rPr></w:lvl></w:abstractNum>',
                 'refs': {'basedOn': 'Normal'},
                 'type': 'paragraph',
                 'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                        'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Bullet"/><w:basedOn '
                        'w:val="{basedOn}"/><w:uiPriority '
                        'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                        'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Bullet 2': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="bullet"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="\uf0b7"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="643"/></w:tabs><w:ind w:left="643" '
                                'w:hanging="360"/></w:pPr><w:rPr><w:rFonts w:ascii="Symbol" w:hAnsi="Symbol" '
                                'w:hint="default"/></w:rPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Bullet 2"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Bullet 3': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="bullet"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="\uf0b7"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="926"/></w:tabs><w:ind w:left="926" '
                                'w:hanging="360"/></w:pPr><w:rPr><w:rFonts w:ascii="Symbol" w:hAnsi="Symbol" '
                                'w:hint="default"/></w:rPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Bullet 3"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Bullet 4': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="bullet"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="\uf0b7"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="1209"/></w:tabs><w:ind w:left="1209" '
                                'w:hanging="360"/></w:pPr><w:rPr><w:rFonts w:ascii="Symbol" w:hAnsi="Symbol" '
                                'w:hint="default"/></w:rPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Bullet 4"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Bullet 5': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="bullet"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="\uf0b7"/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="1492"/></w:tabs><w:ind w:left="1492" '
                                'w:hanging="360"/></w:pPr><w:rPr><w:rFonts w:ascii="Symbol" w:hAnsi="Symbol" '
                                'w:hint="default"/></w:rPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Bullet 5"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Number': {'numbering': '<w:abstractNum '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                              'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                              'w:val="1"/><w:numFmt w:val="decimal"/><w:pStyle w:val="{id}"/><w:lvlText '
                              'w:val="%1."/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                              'w:pos="360"/></w:tabs><w:ind w:left="360" '
                              'w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>',
                 'refs': {'basedOn': 'Normal'},
                 'type': 'paragraph',
                 'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                        'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Number"/><w:basedOn '
                        'w:val="{basedOn}"/><w:uiPriority '
                        'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                        'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Number 2': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="decimal"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="%1."/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="643"/></w:tabs><w:ind w:left="643" '
                                'w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Number 2"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Number 3': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="decimal"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="%1."/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="926"/></w:tabs><w:ind w:left="926" '
                                'w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Number 3"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Number 4': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="decimal"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="%1."/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="1209"/></w:tabs><w:ind w:left="1209" '
                                'w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Number 4"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Number 5': {'numbering': '<w:abstractNum '
                                'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                'w:abstractNumId="{abstract}"><w:nsid w:val="{nsid}"/><w:multiLevelType '
                                'w:val="singleLevel"/><w:tmpl w:val="{tmpl}"/><w:lvl w:ilvl="0"><w:start '
                                'w:val="1"/><w:numFmt w:val="decimal"/><w:pStyle w:val="{id}"/><w:lvlText '
                                'w:val="%1."/><w:lvlJc w:val="left"/><w:pPr><w:tabs><w:tab w:val="num" '
                                'w:pos="1492"/></w:tabs><w:ind w:left="1492" '
                                'w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>',
                   'refs': {'basedOn': 'Normal'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Number 5"/><w:basedOn '
                          'w:val="{basedOn}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:numPr><w:numId '
                          'w:val="{num}"/></w:numPr><w:contextualSpacing/></w:pPr></w:style>'},
 'List Paragraph': {'refs': {'basedOn': 'Normal'},
                    'type': 'paragraph',
                    'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                           'w:type="paragraph" w:styleId="{id}"><w:name w:val="List Paragraph"/><w:basedOn '
                           'w:val="{basedOn}"/><w:uiPriority w:val="34"/><w:qFormat/><w:pPr><w:ind '
                           'w:left="720"/><w:contextualSpacing/></w:pPr></w:style>'},
 'Plain Text': {'refs': {'basedOn': 'Normal', 'link': 'Plain Text Char'},
                'type': 'paragraph',
                'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                       'w:type="paragraph" w:styleId="{id}"><w:name w:val="Plain Text"/><w:basedOn '
                       'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                       'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="0" w:line="240" '
                       'w:lineRule="auto"/></w:pPr><w:rPr><w:rFonts w:ascii="Consolas" w:hAnsi="Consolas" '
                       'w:cs="Consolas"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:style>'},
 'Plain Text Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'Plain Text'},
                     'type': 'character',
                     'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                            'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Plain Text '
                            'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                            'w:val="99"/><w:rPr><w:rFonts w:ascii="Consolas" w:hAnsi="Consolas" '
                            'w:cs="Consolas"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:style>'},
 'Quote': {'refs': {'basedOn': 'Normal', 'link': 'Quote Char', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="Quote"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                  'w:val="29"/><w:qFormat/><w:pPr><w:spacing w:before="200"/><w:ind w:left="864" '
                  'w:right="864"/><w:jc w:val="center"/></w:pPr><w:rPr><w:i/><w:iCs/><w:color w:val="404040" '
                  'w:themeColor="text1" w:themeTint="BF"/></w:rPr></w:style>'},
 'Quote Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'Quote'},
                'type': 'character',
                'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                       'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Quote '
                       'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                       'w:val="29"/><w:rPr><w:i/><w:iCs/><w:color w:val="404040" w:themeColor="text1" '
                       'w:themeTint="BF"/></w:rPr></w:style>'},
 'Strong': {'refs': {'basedOn': 'Default Paragraph Font'},
            'type': 'character',
            'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                   'w:type="character" w:styleId="{id}"><w:name w:val="Strong"/><w:basedOn '
                   'w:val="{basedOn}"/><w:uiPriority '
                   'w:val="22"/><w:qFormat/><w:rPr><w:b/><w:bCs/></w:rPr></w:style>'},
 'Subtitle': {'refs': {'basedOn': 'Normal', 'link': 'Subtitle Char', 'next': 'Normal'},
              'type': 'paragraph',
              'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                     'w:type="paragraph" w:styleId="{id}"><w:name w:val="Subtitle"/><w:basedOn '
                     'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                     'w:val="11"/><w:qFormat/><w:pPr><w:numPr><w:ilvl '
                     'w:val="1"/></w:numPr></w:pPr><w:rPr><w:rFonts w:asciiTheme="minorHAnsi" '
                     'w:eastAsiaTheme="minorEastAsia" w:hAnsiTheme="minorHAnsi" '
                     'w:cstheme="minorBidi"/><w:color w:val="5A5A5A" w:themeColor="text1" '
                     'w:themeTint="A5"/><w:spacing w:val="15"/></w:rPr></w:style>'},
 'Subtitle Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'Subtitle'},
                   'type': 'character',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Subtitle '
                          'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                          'w:val="11"/><w:rPr><w:rFonts w:asciiTheme="minorHAnsi" '
                          'w:eastAsiaTheme="minorEastAsia" w:hAnsiTheme="minorHAnsi" '
                          'w:cstheme="minorBidi"/><w:color w:val="5A5A5A" w:themeColor="text1" '
                          'w:themeTint="A5"/><w:spacing w:val="15"/></w:rPr></w:style>'},
 'Subtle Emphasis': {'refs': {'basedOn': 'Default Paragraph Font'},
                     'type': 'character',
                     'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                            'w:type="character" w:styleId="{id}"><w:name w:val="Subtle Emphasis"/><w:basedOn '
                            'w:val="{basedOn}"/><w:uiPriority '
                            'w:val="19"/><w:qFormat/><w:rPr><w:i/><w:iCs/><w:color w:val="404040" '
                            'w:themeColor="text1" w:themeTint="BF"/></w:rPr></w:style>'},
 'Subtle Reference': {'refs': {'basedOn': 'Default Paragraph Font'},
                      'type': 'character',
                      'xml': '<w:style '
                             'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                             'w:type="character" w:styleId="{id}"><w:name w:val="Subtle '
                             'Reference"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                             'w:val="31"/><w:qFormat/><w:rPr><w:smallCaps/><w:color w:val="5A5A5A" '
                             'w:themeColor="text1" w:themeTint="A5"/></w:rPr></w:style>'},
 'TOC Heading': {'refs': {'basedOn': 'heading 1', 'next': 'Normal'},
                 'type': 'paragraph',
                 'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                        'w:type="paragraph" w:styleId="{id}"><w:name w:val="TOC Heading"/><w:basedOn '
                        'w:val="{basedOn}"/><w:next w:val="{next}"/><w:uiPriority '
                        'w:val="39"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:outlineLvl '
                        'w:val="9"/></w:pPr></w:style>'},
 'Title': {'refs': {'basedOn': 'Normal', 'link': 'Title Char', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="Title"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                  'w:val="10"/><w:qFormat/><w:pPr><w:spacing w:after="0" w:line="240" '
                  'w:lineRule="auto"/><w:contextualSpacing/></w:pPr><w:rPr><w:rFonts '
                  'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                  'w:cstheme="majorBidi"/><w:spacing w:val="-10"/><w:kern w:val="28"/><w:sz '
                  'w:val="56"/><w:szCs w:val="56"/></w:rPr></w:style>'},
 'Title Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'Title'},
                'type': 'character',
                'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                       'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name w:val="Title '
                       'Char"/><w:basedOn w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                       'w:val="10"/><w:rPr><w:rFonts w:asciiTheme="majorHAnsi" '
                       'w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                       'w:cstheme="majorBidi"/><w:spacing w:val="-10"/><w:kern w:val="28"/><w:sz '
                       'w:val="56"/><w:szCs w:val="56"/></w:rPr></w:style>'},
 'caption': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
             'type': 'paragraph',
             'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                    'w:type="paragraph" w:styleId="{id}"><w:name w:val="caption"/><w:basedOn '
                    'w:val="{basedOn}"/><w:next w:val="{next}"/><w:uiPriority '
                    'w:val="35"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:spacing w:after="200" w:line="240" '
                    'w:lineRule="auto"/></w:pPr><w:rPr><w:i/><w:iCs/><w:color w:val="44546A" '
                    'w:themeColor="text2"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style>'},
 'endnote reference': {'refs': {'basedOn': 'Default Paragraph Font'},
                       'type': 'character',
                       'xml': '<w:style '
                              'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                              'w:type="character" w:styleId="{id}"><w:name w:val="endnote '
                              'reference"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                              'w:val="99"/><w:unhideWhenUsed/><w:rPr><w:vertAlign '
                              'w:val="superscript"/></w:rPr></w:style>'},
 'endnote text': {'refs': {'basedOn': 'Normal', 'link': 'Endnote Text Char'},
                  'type': 'paragraph',
                  'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                         'w:type="paragraph" w:styleId="{id}"><w:name w:val="endnote text"/><w:basedOn '
                         'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                         'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="0" w:line="240" '
                         'w:lineRule="auto"/></w:pPr><w:rPr><w:sz w:val="20"/><w:szCs '
                         'w:val="20"/></w:rPr></w:style>'},
 'footer': {'refs': {'basedOn': 'Normal', 'link': 'Footer Char'},
            'type': 'paragraph',
            'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                   'w:type="paragraph" w:styleId="{id}"><w:name w:val="footer"/><w:basedOn '
                   'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                   'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:tabs><w:tab w:val="center" w:pos="4536"/><w:tab '
                   'w:val="right" w:pos="9072"/></w:tabs><w:spacing w:after="0" w:line="240" '
                   'w:lineRule="auto"/></w:pPr></w:style>'},
 'footnote reference': {'refs': {'basedOn': 'Default Paragraph Font'},
                        'type': 'character',
                        'xml': '<w:style '
                               'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                               'w:type="character" w:styleId="{id}"><w:name w:val="footnote '
                               'reference"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                               'w:val="99"/><w:unhideWhenUsed/><w:rPr><w:vertAlign '
                               'w:val="superscript"/></w:rPr></w:style>'},
 'footnote text': {'refs': {'basedOn': 'Normal', 'link': 'Footnote Text Char'},
                   'type': 'paragraph',
                   'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                          'w:type="paragraph" w:styleId="{id}"><w:name w:val="footnote text"/><w:basedOn '
                          'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                          'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="0" w:line="240" '
                          'w:lineRule="auto"/></w:pPr><w:rPr><w:sz w:val="20"/><w:szCs '
                          'w:val="20"/></w:rPr></w:style>'},
 'header': {'refs': {'basedOn': 'Normal', 'link': 'Header Char'},
            'type': 'paragraph',
            'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                   'w:type="paragraph" w:styleId="{id}"><w:name w:val="header"/><w:basedOn '
                   'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                   'w:val="99"/><w:unhideWhenUsed/><w:pPr><w:tabs><w:tab w:val="center" w:pos="4536"/><w:tab '
                   'w:val="right" w:pos="9072"/></w:tabs><w:spacing w:after="0" w:line="240" '
                   'w:lineRule="auto"/></w:pPr></w:style>'},
 'heading 1': {'refs': {'basedOn': 'Normal', 'link': 'Heading 1 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 1"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing w:before="240" '
                      'w:after="0"/><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:color w:val="2F5496" w:themeColor="accent1" '
                      'w:themeShade="BF"/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr></w:style>'},
 'heading 2': {'refs': {'basedOn': 'Normal', 'link': 'Heading 2 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 2"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="1"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:color w:val="2F5496" w:themeColor="accent1" '
                      'w:themeShade="BF"/><w:sz w:val="26"/><w:szCs w:val="26"/></w:rPr></w:style>'},
 'heading 3': {'refs': {'basedOn': 'Normal', 'link': 'Heading 3 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 3"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="2"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:color w:val="1F3763" w:themeColor="accent1" '
                      'w:themeShade="7F"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:style>'},
 'heading 4': {'refs': {'basedOn': 'Normal', 'link': 'Heading 4 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 4"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="3"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:i/><w:iCs/><w:color w:val="2F5496" w:themeColor="accent1" '
                      'w:themeShade="BF"/></w:rPr></w:style>'},
 'heading 5': {'refs': {'basedOn': 'Normal', 'link': 'Heading 5 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 5"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="4"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:color w:val="2F5496" w:themeColor="accent1" '
                      'w:themeShade="BF"/></w:rPr></w:style>'},
 'heading 6': {'refs': {'basedOn': 'Normal', 'link': 'Heading 6 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 6"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="5"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:color w:val="1F3763" w:themeColor="accent1" '
                      'w:themeShade="7F"/></w:rPr></w:style>'},
 'heading 7': {'refs': {'basedOn': 'Normal', 'link': 'Heading 7 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 7"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="6"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:i/><w:iCs/><w:color w:val="1F3763" w:themeColor="accent1" '
                      'w:themeShade="7F"/></w:rPr></w:style>'},
 'heading 8': {'refs': {'basedOn': 'Normal', 'link': 'Heading 8 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 8"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="7"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:color w:val="272727" w:themeColor="text1" '
                      'w:themeTint="D8"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:style>'},
 'heading 9': {'refs': {'basedOn': 'Normal', 'link': 'Heading 9 Char', 'next': 'Normal'},
               'type': 'paragraph',
               'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                      'w:type="paragraph" w:styleId="{id}"><w:name w:val="heading 9"/><w:basedOn '
                      'w:val="{basedOn}"/><w:next w:val="{next}"/><w:link w:val="{link}"/><w:uiPriority '
                      'w:val="9"/><w:unhideWhenUsed/><w:qFormat/><w:pPr><w:keepNext/><w:keepLines/><w:spacing '
                      'w:before="40" w:after="0"/><w:outlineLvl w:val="8"/></w:pPr><w:rPr><w:rFonts '
                      'w:asciiTheme="majorHAnsi" w:eastAsiaTheme="majorEastAsia" w:hAnsiTheme="majorHAnsi" '
                      'w:cstheme="majorBidi"/><w:i/><w:iCs/><w:color w:val="272727" w:themeColor="text1" '
                      'w:themeTint="D8"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:style>'}}
