"""Word's TOC 1-9 styles, as Word 16.106 writes them with a table of contents.

Generated by ``tools/e4_probe.py`` from the probe Word saved (the observations are in
``tests/observations/e4-word.json``); do not edit by hand.  The same form as
``word_styles.py``: keyed by ``w:name``, ``{id}`` and the references filled in when written.
"""

STYLES: dict[str, dict] = {'toc 1': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 1"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing '
                  'w:after="100"/></w:pPr></w:style>'},
 'toc 2': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 2"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="220"/></w:pPr></w:style>'},
 'toc 3': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 3"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="440"/></w:pPr></w:style>'},
 'toc 4': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 4"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="660"/></w:pPr></w:style>'},
 'toc 5': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 5"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="880"/></w:pPr></w:style>'},
 'toc 6': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 6"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="1100"/></w:pPr></w:style>'},
 'toc 7': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 7"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="1320"/></w:pPr></w:style>'},
 'toc 8': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 8"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="1540"/></w:pPr></w:style>'},
 'toc 9': {'refs': {'basedOn': 'Normal', 'next': 'Normal'},
           'type': 'paragraph',
           'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                  'w:type="paragraph" w:styleId="{id}"><w:name w:val="toc 9"/><w:basedOn '
                  'w:val="{basedOn}"/><w:next w:val="{next}"/><w:autoRedefine/><w:uiPriority '
                  'w:val="39"/><w:unhideWhenUsed/><w:pPr><w:spacing w:after="100"/><w:ind '
                  'w:left="1760"/></w:pPr></w:style>'}}
