"""The styles Word 16.106 adds with a document's first comment, as it writes them.

Generated by ``tools/e3_probe.py`` from the tracked probe Word saved (the observations are
in ``tests/observations/e3-word.json``); do not edit by hand.  The same form as
``word_styles.py``: keyed by ``w:name``, ``{id}`` and the references filled in when written.
"""

STYLES: dict[str, dict] = {'Annotation Subject Char': {'refs': {'basedOn': 'Annotation Text Char', 'link': 'annotation subject'},
                             'type': 'character',
                             'xml': '<w:style '
                                    'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                    'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name '
                                    'w:val="Annotation Subject Char"/><w:basedOn w:val="{basedOn}"/><w:link '
                                    'w:val="{link}"/><w:uiPriority '
                                    'w:val="99"/><w:semiHidden/><w:rPr><w:b/><w:bCs/><w:sz '
                                    'w:val="20"/><w:szCs w:val="20"/></w:rPr></w:style>'},
 'Annotation Text Char': {'refs': {'basedOn': 'Default Paragraph Font', 'link': 'annotation text'},
                          'type': 'character',
                          'xml': '<w:style '
                                 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                 'w:type="character" w:customStyle="1" w:styleId="{id}"><w:name '
                                 'w:val="Annotation Text Char"/><w:basedOn w:val="{basedOn}"/><w:link '
                                 'w:val="{link}"/><w:uiPriority w:val="99"/><w:semiHidden/><w:rPr><w:sz '
                                 'w:val="20"/><w:szCs w:val="20"/></w:rPr></w:style>'},
 'annotation reference': {'refs': {'basedOn': 'Default Paragraph Font'},
                          'type': 'character',
                          'xml': '<w:style '
                                 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                                 'w:type="character" w:styleId="{id}"><w:name w:val="annotation '
                                 'reference"/><w:basedOn w:val="{basedOn}"/><w:uiPriority '
                                 'w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:rPr><w:sz '
                                 'w:val="16"/><w:szCs w:val="16"/></w:rPr></w:style>'},
 'annotation subject': {'refs': {'basedOn': 'annotation text',
                                 'link': 'Annotation Subject Char',
                                 'next': 'annotation text'},
                        'type': 'paragraph',
                        'xml': '<w:style '
                               'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                               'w:type="paragraph" w:styleId="{id}"><w:name w:val="annotation '
                               'subject"/><w:basedOn w:val="{basedOn}"/><w:next w:val="{next}"/><w:link '
                               'w:val="{link}"/><w:uiPriority '
                               'w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:rPr><w:b/><w:bCs/></w:rPr></w:style>'},
 'annotation text': {'refs': {'basedOn': 'Normal', 'link': 'Annotation Text Char'},
                     'type': 'paragraph',
                     'xml': '<w:style xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
                            'w:type="paragraph" w:styleId="{id}"><w:name w:val="annotation text"/><w:basedOn '
                            'w:val="{basedOn}"/><w:link w:val="{link}"/><w:uiPriority '
                            'w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:pPr><w:spacing w:line="240" '
                            'w:lineRule="auto"/></w:pPr><w:rPr><w:sz w:val="20"/><w:szCs '
                            'w:val="20"/></w:rPr></w:style>'}}
